# Generated by Django 6.0.3 on 2026-04-08 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_category_options'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['-active'], name='products_pr_active_ba1a9a_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['-price'], name='products_pr_price_5bbd2d_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['name'], name='products_pr_name_9ff0a3_idx'),
        ),
    ]
