# Generated by Django 6.0.3 on 2026-04-08 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_products_pr_active_ba1a9a_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='product',
            name='products_pr_active_ba1a9a_idx',
        ),
    ]
