# Generated by Django 6.0.3 on 2026-04-08 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_remove_product_products_pr_active_ba1a9a_idx'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-active', 'category', 'name', 'price'], 'verbose_name': 'Produkt', 'verbose_name_plural': 'Produkte'},
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='products_pr_price_5bbd2d_idx',
        ),
    ]
