# Generated by Django 6.0.3 on 2026-04-10 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_jobs'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='jobs',
            unique_together={('name', 'salary')},
        ),
    ]
